## Python Version:3.12
FROM python:3.12-slim-trixie

COPY pip.conf /etc/pip.conf

RUN apt-get update && apt-get install -y libmagic1 poppler-utils

# appディレクトリを作成
WORKDIR /app

# 必要なPythonライブラリのインストール
COPY requirements.txt /app
RUN pip install --upgrade pip && pip install -r requirements.txt

# プログラムや設定ファイルなどをコピーする
COPY main.py /app
COPY modules/ /app/modules/
